#!/bin/bash
printf '\n=== Running post-deploy action hook ===\n\n'

if [ -z "$VIRTUAL_ENV" ]; then
    echo "Activating virtialenv environamnt"
    source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
fi


if [ "$OPENSHIFT_GEAR_NAME" != "$OPENSHIFT_GEAR_UUID" ]; then
  echo "Runing on head gear"
  cd $OPENSHIFT_REPO_DIR

  printf "\nRebuilding supervisord config and restarting worker\n"
  make create-leagent-conf
  make create-supervisord-conf
  supervisorctl -c supervisord.conf reload

else
  echo "Running on slave gear"
fi
