#!/bin/bash
printf '\n=== Running post-deploy action hook ===\n\n'

# First check if we are running on Openshift
if [ -z "$OPENSHIFT_GEAR_NAME" ]; then
    echo "Not running on Openshift"
    exit 0
fi

if [ -z "$VIRTUAL_ENV" ]; then
    echo "Activating virtialenv environamnt"
    source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate
fi


if [ "$OPENSHIFT_GEAR_NAME" != "$OPENSHIFT_GEAR_UUID" ]; then
  echo "Runing on head gear, rebuilding supervisord config and restarting worker"
  cd $OPENSHIFT_REPO_DIR
  make create-leagent-conf
  make create-supervisord-conf
  supervisorctl -c supervisord-openshift.conf reload

else
  echo "Running on slave gear"
fi
